export const siteConfig = {
  name: "Majid Niyaz | Data Platform Engineer",
  authorName: "Majid Niyaz",
  username: "majidmisger",
  description:
    "Majid Niyaz's portfolio — Data Platform Engineer at Wingify, working on VWO with the Data Layer team in Engineering. Building scalable analytics systems with BigQuery, ClickHouse, Bigtable, GCS, and Kafka.",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https://x.com/Majid_riaz_",
    github: "https://github.com/majidmisger",
    linkedin: "https://www.linkedin.com/in/majid-misger/",
  },
  ogImage: "/majid-img.png",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/majid-favicon.ico",
  logoIcon: "/majid-logo.png",
  keywords: [
    "Majid Niyaz",
    "Data Platform Engineer",
    "VWO",
    "Wingify",
    "BigQuery",
    "ClickHouse",
    "Bigtable",
    "GCS",
    "Google Cloud Storage",
    "Kafka",
    "GCP",
    "Backend Developer",
    "Node.js Developer",
    "TypeScript Developer",
    "PostgreSQL Developer",
    "Redis Caching",
    "Real-time analytics",
    "ETL pipelines",
    "API Performance",
    "GraphQL APIs",
    "REST APIs",
    "Scalable Backend Architecture",
    "Website Optimizer",
    "Experimentation analytics",
    "Majid Portfolio",
    "Event-driven systems",
    "Next.js Portfolio",
  ],
};
